### ISSUE TITLE
Improve LCP accuracy by ignoring some clicks/keypresses

### ISSUE THREAD

**Issue by smhmic** [GoogleChrome/web-vitals#101]
Right now the library allows inert clicks and keypresses (i.e. user clicks on 'loading' gif) to skew LCP scores lower. Two ideas for mitigating this:

1. Do not allow user clicks and keypresses to deactivate LCP monitoring until FID.
2. Offer a way to customize which inputs/elements deactivate LCP monitoring.

**Comment by philipwalton** [comment]
This library adds a `click` and `keydown` listener just as a means of reporting the "final" LCP value sooner. It does this because the underlying [Largest Contentful Paint API](https://wicg.github.io/largest-contentful-paint/#sec-modifications-DOM) itself will stop listening for new largest paints after user input or scrolls (see https://github.com/GoogleChrome/web-vitals/issues/75 to know why this library stopped listening for the `scroll` event).

If https://github.com/WICG/largest-contentful-paint/issues/43 in the LCP spec is addressed, this library will not have to use the `click` and `keydown` listeners, and it can just rely on the underlying API to know when observation has stopped.

**Comment by philipwalton** [comment]
I'm going to close this issue since I don't think there's any action this library needs to take at this time.
