### ISSUE TITLE
`content-visibility: auto;` makes CLS go bananas

### ISSUE THREAD

**Issue by zeemawn** [GoogleChrome/web-vitals#108]
I've added

```
content-visibility: auto;
contain-intrinsic-size: 0 500px;
```

to several content sections on my page.

As a result, I'm getting crazy values for the CLS-metric, the value even keeps increasing while I'm scrolling up and down the page:

![image](https://user-images.githubusercontent.com/15956661/102366361-dd0bc300-3fb8-11eb-82ab-6fcddc167764.png)

I see why the value would be measured like this from a technical perspective - however the UX is not actually affected, as all of the magic is happening outside of the viewport.

Do I need to be afraid of being penalized for this in the upcoming ranking-algorithm change?

**Comment by philipwalton** [comment]
Can you try with Chrome 88? I believe you're describing what was fixed in [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1151526), which was merged into Chrome 88.

> Do I need to be afraid of being penalized for this in the upcoming ranking-algorithm change?

In general, my advice is to do what you've done, and report any issues where you feel like the metrics are not accurately reflecting the user experience. If you're seeing that happen (and it feels wrong to you), most likely it's a bug, and if you report it we'll prioritize fixing it.

In this case, the `web-vitals` library is just reporting the shifts that the Layout Instability API is reporting to it, so I don't think any action needs to be taken in this repo.

**Comment by zeemawn** [comment]
Thanks, for your answer, here some further investigation:

Example: https://jsfiddle.net/qmdaj6r1/1/

Some remarks
* tested in Chrome 87 & Chrome Canary 89
* whenever you scroll down/up and the yellow/red paragraph change their size, the CLS-value increases for quite a bit
* somehow JSFiddle seems to have some performance-issues with these calculations, this is something I haven't experienced in production though

**Comment by anniesullie** [comment]
Looks like this is a bug in Chrome, so I moved the bug there: https://bugs.chromium.org/p/chromium/issues/detail?id=1164942

Closing this issue, but if there's a specification question that arises from that bug we can open a new issue in this repo.
