### ISSUE TITLE
CLS - Counting not the real layout shift from UX

### ISSUE THREAD

**Issue by kajman-cz** [GoogleChrome/web-vitals#121]
Should the LS be counted if there is a change in the DOM that the user cannot see with the eyes? For example, when wrap the 
infinite carousel from end to start (move the first item to the end of list and back to start).

[Test page](http://kod.djpw.cz/dlad-)

![wrapAround-CLS](https://user-images.githubusercontent.com/45236547/106199203-67009b80-61b5-11eb-8a8d-62f3a6cb652b.png)

**Comment by philipwalton** [comment]
To answer your question: no, it generally should not be considered a layout shift if you can't see the layout shift with your eyes.

That being said, I do not see any layout shifts reported when viewing that page in Chrome 88. Can you make sure you're up-to-date with the latest Chrome version? Several CLS bugs were fixed in Chrome 88 that could be affecting what you're seeing.

If you're still seeing shifts, then please file a Chrome bug at crbug.com, as this would be a Chrome issue and not an issue with this library.
