### ISSUE TITLE
Are CLS values above 100% valid?

### ISSUE THREAD

**Issue by elstgav** [GoogleChrome/web-vitals#126]
We recently implemented the library and are seeing some strangely high CLS values—some desktop Chrome browsers are reporting values as high as 513% — are those valid values? I’ve been going off the assumption that for CLS, `1.0` is equivalent to `100%`. 

I haven’t been able to reproduce the CLS values in my own Chrome browser on the Mac, and am not sure how to interpret these results, or determine if they’re invalid.

**Comment by philipwalton** [comment]
> ...are those valid values? I’ve been going off the assumption that for CLS, `1.0` is equivalent to `100%`.

This is not a correct assumption. There is no max on CLS, since a website could potentially have an unlimited number of layout shifts.

The [layout shift score](https://web.dev/cls/#layout-shift-score) measures how much of the visible content inside the viewport shifts, and it's weighted by how far it shifted.

For example: if everything inside of the viewport shifted out of the viewport in a single frame, that would have a layout shift score of `1.0`, and if that happened 10 times during the lifecycle of a page, the CLS value would be `10.0`.

> I haven’t been able to reproduce the CLS values in my own Chrome browser on the Mac, and am not sure how to interpret these results, or determine if they’re invalid.

See #123 for some suggestions around how best to do this.

The main thing I want to point out (since lots of people seem to be confused by this) is that CLS is not just measured during page load. It's measure for the *entire time* the page is visible to the user, including shifts that occur as a result of user interactions.

I hope that helps!

**Comment by elstgav** [comment]
Thanks @philipwalton, that makes sense. I think [the link you provided](https://web.dev/cls/#layout-shift-score) would be more helpful than [the WICG spec](https://wicg.github.io/layout-instability/#layout-shift-value) in the docs, e.g.

> `getCls()`
>
> Calculates the [CLS](https://web.dev/cls/) value for the current page … The reported value is a [double](https://heycam.github.io/webidl/#idl-double) (corresponding to a ~[layout shift value](https://wicg.github.io/layout-instability/#layout-shift-value)~ [layout shift score](https://web.dev/cls/#layout-shift-score)). 

I may need to start logging the contributing element like you mention in #123, as I haven’t been able to figure out the culprit!

**Comment by philipwalton** [comment]
Good suggestion! I updated the README.
