### ISSUE TITLE
CLS impacted by element not visible

### ISSUE THREAD

**Issue by Ludovic33Fr** [GoogleChrome/web-vitals#129]
Hello, 

It seems that the metric CLS is impacted by any elements not visible by human. 
For instance if an invisible element located behind an overlay (ZIndex usage) shifts then the metric is impacted whereas it is not visible. 

This is not consistent with the definition of the metric.

I think that it could be fix into implementation of metrics because visibility is well done when we use property like : opacity visibility or display.

**Comment by philipwalton** [comment]
Several bugs related to `layout-shift` entries being reported for invisible elements have been fixed in Chrome recently. See the metrics [CHANGELOG](https://chromium.googlesource.com/chromium/src/+/master/docs/speed/metrics_changelog/README.md) for more details. In summary, elements that are either `display:none`, `visibility:hidden`, or `opacity:0` should not trigger layout shifts.

In general, it's a good idea to test your site in Chrome Canary before reporting bugs because in some cases the bugs have already been fixed.

As for the issue of `z-index` and stacking order, here you're correct that the intention of the metric is not being honored, and these layout shifts are reported even though they're not visible. We'd like to eventually find a way to ignore these, but (speaking at least for Chrome) attempting to ignore shifts that are invisible due to stacking order is not possible to do currently without negatively affecting performance. So the advice is: if you have items that you know might shift, hide them with `visibility` or `opacity` until you need to show them.
