### ISSUE TITLE
Scroll position at CLS events

### ISSUE THREAD

**Issue by michaelterryio** [GoogleChrome/web-vitals#134]
Since pages are penalized for shifts over the lifetime of the page, they can happen at any scroll position. Can this lib add scroll position to the data it emits? As far as I know `DOMRects` are relative to the viewport.

I'm looking to make a userscript/extension to overlay the page with rectangles representing shifts, but I don't think I can without scroll info.

Thoughts?

**Comment by Tiggerito** [comment]
I've just implemented an overlay script and noticed the same thing. Adding the current scroll position to the rect at the time of the event puts the overlays in a better position.

**Comment by philipwalton** [comment]
> Can this lib add scroll position to the data it emits? As far as I know `DOMRects` are relative to the viewport.

Unfortunately, this lib can only expose what's available in the underlying web API, so in order to expose this we'd have to update the [Layout Instability API](https://wicg.github.io/layout-instability/) spec (and then the Chrome implementation).

I'd recommended opening a [new issue](https://github.com/WICG/layout-instability/issues) in the Layout Instability Spec repo proposing this feature.

**Comment by michaelterryio** [comment]
I was afraid of that. Thanks!
