### ISSUE TITLE
What's different from lighthouse?

### ISSUE THREAD

**Issue by zengzuo613** [GoogleChrome/web-vitals#150]
# question
I use web-vitals to find out the reason why the actual page is slow and use lighthouse to locate the reason. Lighthouse also has TTFB, FCP, LCP, FID, CLS and other indicators. Do lighthouse and web vitals use the same algorithm？Are the statistics the same？

**Comment by philipwalton** [comment]
The metrics are the same, but there could be differences because Lighthouse is run in a simulated environment, with no user, and only runs during page load.

This post goes into some of the differences between the two environments:
https://www.onely.com/blog/measuring-web-performance-lab-vs-field-data/
