### ISSUE TITLE
getEntriesByName is not supported in some versions of Opera

### ISSUE THREAD

**Issue by jroebu14** [GoogleChrome/web-vitals#159]
Hi there,

We noticed that upgrading from v1.1.1 to v1.1.2 broke our application for our users on data saving mode in the Opera Mini browser.

We believe it was caused by this change https://github.com/GoogleChrome/web-vitals/commit/4dfde193e0c7f7d1dbb002a33c92128fa6ad54c1

It seems that `performance.getEntriesByName` is [not supported in some version of Opera](https://caniuse.com/?search=getEntriesByName).

So that we can upgrade the web-vitals package in our application, would you recommend we look for a polyfill for `performance.getEntriesByName` or should we contribute a fix?

Thanks

**Comment by philipwalton** [comment]
The fix for this was released in [v2.0.1](https://github.com/GoogleChrome/web-vitals/blob/master/CHANGELOG.md#v201-2021-06-02), so you'll have to do a major version update to get it, but hopefully that's not a problem?

There was minimal breaking changes in the v2 update, mostly just the change to how CLS is calculated which you'll probably want to update to get anyway.

**Comment by jroebu14** [comment]
Thanks for your help, @philipwalton. Yeh I don't think upgrading to v2 will be an issue 🙂
