### ISSUE TITLE
Chrome 70 does not support supportedentrytypes

### ISSUE THREAD

**Issue by yangdan8** [GoogleChrome/web-vitals#179]
Code: `PerformanceObserver.supportedEntryTypes.includes('first-input')`
Error: `Uncaught TypeError: Cannot read property 'includes' of undefined`
`largest-contentful-paint` is also not supported

**Comment by philipwalton** [comment]
The only reference to `supportedEntryTypes` is in a try/catch block: https://github.com/GoogleChrome/web-vitals/blob/cfe7536dc8f13e3cbbbf48436328f52399dd6725/src/lib/observe.ts#L33-L49

Can you confirm that you're using the latest version of the library and that the error you're seeing isn't being thrown somewhere else in your code?

**Comment by wxsms** [comment]
I also have to use web-vitals on chrome 70. which throws no error, but doesn't work at all (with or without polyfill).

Looks like `supportedEntryTypes` is supported since chrome 73:

![image](https://user-images.githubusercontent.com/5960988/147625519-4b5b8981-2a8a-4cda-a46b-844c5fba77c8.png)

is there any workaround?

**Comment by philipwalton** [comment]
`getFID()` should work on Chrome 70 with the polyfill. None of the other functions are expected to work because the APIs for them were added in later versions.

If you're not seeing any errors thrown on Chrome 70 then everything is working as expected.
