### ISSUE TITLE
Create new metrics (FPS)

### ISSUE THREAD

**Issue by pan-alexey** [GoogleChrome/web-vitals#194]
I would like to add an FPS counter. The measurement will be "requestAnimationFrame" or "PerfomanceObserver" with entries by "frame". The metric will be sent at the same moment as the CLS. The value will be the minimum of all measurements.
Also, at the moment of scrolling, the measurement will be ignored. How do you like this idea and such a metric?

**Comment by philipwalton** [comment]
Hey @pan-alexey, for context, this library only includes metrics that are officially part of the [Web Vitals](https://web.dev/vitals/) initiative within Chrome. There are a number of very useful performance metrics that it could measure and expose, but we've intentionally limited it to just the Web Vitals metrics too keep the library small and focused.

That being said, the Chrome team is exploring a metric that's very similar to the one you're describing. I'd recommended taking a look at it here: https://web.dev/smoothness/

Also note that the post specifically discourages the use of `requestAnimationFrame()` as a means of measurement, which is why a new Web API is required for this use case.
