### ISSUE TITLE
Questions about canceling event listeners

### ISSUE THREAD

**Issue by karl-coder** [GoogleChrome/web-vitals#199]
Thank you for your contributions, and i have some questions about  LCP observation.
1: When requesting data, the page only has a loading icon, and the user clicks on the page at this time, the LCP observation will be stopped, but the pages that depend on the data are not actually rendered yet.
2: The scroll event will not stop the LCP observation, so there is another situation. a larger image is lazy loaded when scrolling to the bottom of the page, Since the LCP is staged,  the LCP is very large at this time, but in fact this value is not needed
Is this as expected? Or is it an extreme case？

**Comment by philipwalton** [comment]
Any user interaction with the page will stop further LCP observation. See [this section of the LCP documentation page](https://web.dev/lcp/#:~:text=The%20browser%20will%20stop%20reporting%20new%20entries%20as%20soon%20as%20the%20user%20interacts%20with%20the%20page%20(via%20a%20tap%2C%20scroll%2C%20or%20keypress)%2C%20as%20user%20interaction%20often%20changes%20what%27s%20visible%20to%20the%20user%20(which%20is%20especially%20true%20with%20scrolling).) for more details.

While it's true that in some cases observation will stop before the largest content is rendered, not doing this would be worse because the metric value would then be dependant on user interactions (e.g. if a user waited 10 seconds and then scrolled down to view a large image, LCP would be 10 seconds, even if the image finished loading much earlier).

**Comment by karl-coder** [comment]
Thank you for your reply. After reading the document, it is much clearer. In user interaction events, click and keydown events will be canceled in advance by web-vitals, and scroll is controlled by largest-contentful-paint itself. I should accept that there is really no perfect solution for some special cases.
