### ISSUE TITLE
Utility for checking a metric passes the threshold?

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/web-vitals#2]
When I first started using the library, I was a little surprised to see it didn't implement a canonical helper for determining if a metric passed the Core Web Vitals thresholds. 

While our documentation on web.dev captures what the thresholds are, I can imagine there is value to a developer not needing to hardcode threshold values themselves (e.g imagine if they got this subtly wrong). 

I currently implement custom scoring logic in the WIP web vitals extension, but thought I'd throw this idea over the fence to see what you thought. 

I'll defer on the API shape if you think this would be helpful, but you could loosely imagine...

```js
getCLS((result) => logCurrentValue('cls', result.value, result.passesThreshold, result.isFinal));
```

**Comment by Zizzamia** [comment]
How about a threshold set as an optional value for each metric? In the README, you can recommend the developer the optimal value to benchmark, and it still gives the developer the opportunity to change it when they prefer.

We could see this as a budget for those metrics, where the developer can customize the value where they are pushing for.

**Comment by philipwalton** [comment]
I've gone back and forth on whether we should support this, but ultimately I haven't been able to come up with an API that works well. Since the thresholds are [well-documented publicly](https://web.dev/vitals/#core-web-vitals), I think it makes sense for developers who want to track threshold compliance to do so in their own code.

Some of the reasons for my thinking:

- Thresholds might change over time, and a user might not necessarily want to update their version of this library just to get new thresholds
- Not all of the metrics have published thresholds, nor do we plan on publishing thresholds for all metrics, so adding that would make the interface for the `Metric` object inconsistent (e.g. TTFB is unlikely to have a published threshold)
- Including the thresholds adds extra weight to the library (albeit small) for many users who may not need it
