### ISSUE TITLE
CSS Tooltip is triggering an LCP event

### ISSUE THREAD

**Issue by Tiggerito** [GoogleChrome/web-vitals#234]
An issue was raised on [stackoverflow](https://stackoverflow.com/questions/72509057/css-tooltip-harmful-for-largest-contentful-paint-how-to-resolve).

I managed to reproduce it using getLCP(myFunction, true); It can also be seen with the Web Vitals extension.

If you hover over the CSS tooltip before interacting with the page, it fires an LCP event for the time you hovered over it, which becomes your LCP score.

Here's a console log of the event with the tooltip as one of the LCPs.

![image](https://user-images.githubusercontent.com/4947018/172096039-9ad0877f-263e-44b9-bacb-5e690b455780.png)

I'm guessing the issue may be that this type of user interaction is not detected?

**Comment by philipwalton** [comment]
Thanks for the report. This is a known issue with LCP measurement in Chrome, and there is ongoing work to better measure how often it is happening and what the best fix is. See this bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=1288027

I'm going to close this issue in this repo because there's not really anything that this library can do to address the problem. If/when a fix is implemented in the browser API, this library will automatically pick that up.
