### ISSUE TITLE
ReferenceError: addEventListener is not defined `v3.0.1`

### ISSUE THREAD

**Issue by brmendez** [GoogleChrome/web-vitals#258]
I have just upgraded to `v3.0.1` and am now getting this error when any of my tests reference `onFCP()`:
```
ReferenceError: addEventListener is not defined
      at l (node_modules/web-vitals/dist/web-vitals.umd.cjs:1:1249)
      at h (node_modules/web-vitals/dist/web-vitals.umd.cjs:1:1649)
      at g (node_modules/web-vitals/dist/web-vitals.umd.cjs:1:1725)
      at y (node_modules/web-vitals/dist/web-vitals.umd.cjs:1:1865)
```
_Originally posted by @brmendez in https://github.com/GoogleChrome/web-vitals/issues/256#issuecomment-1233533392_

FYI - I plan on stubbing this method, but wanted to know if this is expected?

**Comment by philipwalton** [comment]
> FYI - I plan on stubbing this method, but wanted to know if this is expected?

This is expected. The philosophy I've taken with this library is that I want to support the ability to import the library in node without error, but I don't think it's reasonable to support running the individual functions themselves in node, especially since the APIs needed to support these functions are only available in the browser.

Most web frameworks I'm familiar with have dedicated solutions for this problem, e.g. React has a [`useEffect()` hook](https://reactjs.org/docs/hooks-effect.html) which it specifically recommends developers use for browser-only code if they always want to use React SSR methods for their app. Have you tried something like that?

Also, FWIW, I get a different error when I try to call `onFCP()` in node:

```
Uncaught ReferenceError: document is not defined
    at m (/Users/philipwalton/Projects/GoogleChrome/web-vitals/dist/web-vitals.umd.cjs:1:1581)
    at g (/Users/philipwalton/Projects/GoogleChrome/web-vitals/dist/web-vitals.umd.cjs:1:1721)
    at Object.y (/Users/philipwalton/Projects/GoogleChrome/web-vitals/dist/web-vitals.umd.cjs:1:1865)
```

Presumably this is because your code is already stubbing `document`?

**Comment by brmendez** [comment]
Sorry for delay, thanks for the response!

> This is expected. The philosophy I've taken with this library is that I want to support the ability to import the library in node without error, but I don't think it's reasonable to support running the individual functions themselves in node, especially since the APIs needed to support these functions are only available in the browser.

Gotcha, I am trying to capture these in an analytics data layer on the client. These are captured on page-views and link-clicks (not sure if link clicks are necessary as they may have the same state as the previous page-view) and sent off to our performance team to be measured.

> Most web frameworks I'm familiar with have dedicated solutions for this problem, e.g. React has a [`useEffect()` hook](https://reactjs.org/docs/hooks-effect.html) which it specifically recommends developers use for browser-only code if they always want to use React SSR methods for their app. Have you tried something like that?

The library that captures these metrics (via `web-vitals`) is written in vanilla JS. If not to simply stub `onFCP()`, do you have any recommendations for testing `web-vitals` in vanilla JS?

Regardless, this is good to know as the consuming applications run Vue.js. Looks like they can use [`watch`](https://vuejs.org/guide/essentials/watchers.html#basic-example). 

> Also, FWIW, I get a different error when I try to call `onFCP()` in node:
> 
> ```
> Uncaught ReferenceError: document is not defined
>     at m (/Users/philipwalton/Projects/GoogleChrome/web-vitals/dist/web-vitals.umd.cjs:1:1581)
>     at g (/Users/philipwalton/Projects/GoogleChrome/web-vitals/dist/web-vitals.umd.cjs:1:1721)
>     at Object.y (/Users/philipwalton/Projects/GoogleChrome/web-vitals/dist/web-vitals.umd.cjs:1:1865)
> ```
> 
> Presumably this is because your code is already stubbing `document`?

Yes, you are correct. Using `JSDOM`, which stubs `window`/`document`.

Feel free to close this if not qualified as an issue. I appreciate the response! 🍻

**Comment by philipwalton** [comment]
> If not to simply stub `onFCP()`, do you have any recommendations for testing `web-vitals` in vanilla JS?

I think I would just stub `onFCP()`. The `web-vitals` library has extensive tests, so I think it's reasonable for your code to only be testing what happens when `onFCP()` is called, and not testing that it's called in X set of conditions. 

If you do want to test that it's called in certain conditions, I'd test it in a real browser via something like webdriver, puppeteer, or playwrite. I wouldn't test it in node.
