### ISSUE TITLE
onLCP does not work on prerendered pages

### ISSUE THREAD

**Issue by domenic** [GoogleChrome/web-vitals#268]
Steps to reproduce:

- I'm using Chrome 108.0.5355.0 (Official Build) dev (64-bit) ; maybe be sure to be at least at that revision.
- Enable Prerender2 in chrome://flags. Not sure this is necessary anymore but let's just be sure.
- Visit https://equatorial-longing-kick.glitch.me/ .
- Click "This link should be prerendered"
- Notice that the page was prerendered (`document.prerendering` was logged as true), but no LCP is logged.
- Open a new tab, directly to https://equatorial-longing-kick.glitch.me/next.html .
- Notice that this time we get LCP logged.

So it seems like if the page is loaded while prerendered, onLCP is never called. Maybe this is related to the README saying

> CLS, FCP, FID, and LCP are not reported if the page was loaded in the background.

I noticed that there is some special handling for bfcache restore in https://github.com/GoogleChrome/web-vitals/blob/main/src/onLCP.ts#L92-L106 . Maybe there should be something similar for prerendering activation? (Prerendering activation can be detected using the `prerenderingchange` event on `Document`.)

**Comment by tunetheweb** [comment]
@philipwalton I think this is due to a combination of this:

https://github.com/GoogleChrome/web-vitals/blob/dfbd06e2fbdf8d8c8c7e252f710d66c5bbad10a0/src/onLCP.ts#L54-L58

And this:

https://github.com/GoogleChrome/web-vitals/blob/dfbd06e2fbdf8d8c8c7e252f710d66c5bbad10a0/src/lib/bindReporter.ts#L40

As the LCP time for a prerendered page should always be less than the activation time, we get a negative LCP, and that is then filtered out. We should clamp it to 0, same as we do for TTFB.

I've tested with a copy of @domenic 's demo page here and it seem's to work: https://prerender-demos.glitch.me/

Presumably should do same for FCP too.

Happy to put together a PR if you agree.
