### ISSUE TITLE
Correctly measuring a CLS score of 0

### ISSUE THREAD

**Issue by gbrlmtrz** [GoogleChrome/web-vitals#296]
Sorry in advance if this is not the right place to ask this.

I was wondering if it is correct to assume that if the callback for onCLS is never called, then the CLS score for a page is 0. I see [here](https://github.com/GoogleChrome/web-vitals/blob/main/src/onCLS.ts#L117-L123) that the callback could potentially be triggered with 0 after FCP is calculated, but I am not sure how this behavior is supposed to work on all use cases.

Thanks!

**Comment by philipwalton** [comment]
> I was wondering if it is correct to assume that if the callback for onCLS is never called, then the CLS score for a page is 0.

That is not correct. If the CLS value is 0 then the callback will be called with 0. If the `onCLS()` callback is never called then it means either the browser doesn't support CLS or the page didn't reach FCP (which is often the case if the page was loaded in a background tab).

Note that by default the callback for `onCLS()` only fires when the page's visibility state changes to hidden, so it's possible it is firing but you're not noticing it because you're expecting it to fire once the page is done loading. If you switch tabs and then switch back, you should see something logged (you can also refresh and make sure "preserve log" is checked in DevTools).

**Comment by gbrlmtrz** [comment]
Thank you very much for the promptly answer! We will adjust our logic to that!
