### ISSUE TITLE
Guidance to analytics providers on handling metric updates

### ISSUE THREAD

**Issue by scheler** [GoogleChrome/web-vitals#298]
From reading https://github.com/GoogleChrome/web-vitals#report-only-the-delta-of-changes it looks like the guidance for analytics providers when a metric's value changes is to collect all the updates and but only use the last one for the purpose of analytics.

This imposes a requirement that the providers keep all the original metrics in a data store and makes it hard to precompute histograms as it's not possible to override previous observations in a histogram. So, i am wondering what the guidance is if we want to build histogram during ingestion time.

cc: @shumone

**Comment by philipwalton** [comment]
> So, i am wondering what the guidance is if we want to build histogram during ingestion time.

Can you be more specific about what you mean by "ingestion time".

> This imposes a requirement that the providers keep all the original metrics in a data store and makes it hard to precompute histograms as it's not possible to override previous observations in a histogram.

I understand your comment about making it hard to update histograms after they've already been computed, but isn't it always a requirement to keep original metric data around, e.g. if you want to display weekly or monthly histograms later?

**Comment by scheler** [comment]
> I understand your comment about making it hard to update histograms after they've already been computed, but isn't it always a requirement to keep original metric data around, e.g. if you want to display weekly or monthly histograms later

I am learning about histograms as we speak. My understanding so far is that they can answer the different time-series queries with approximation, so you don't really need to keep the original data. And, even if you have the original data around the read time percentile calculations would be a different approach than precomputing the histogram as the data arrives. Histogram metric type is commonly supported by several metrics platforms, hence I was leaning towards using them. However, they do not allow replacing prior observations.

**Comment by philipwalton** [comment]
I'm not sure I understand what specific question you're asking. Can you clarify what exactly you're trying to do and what you're having trouble with?

**Comment by scheler** [comment]
We want to collect the core web vitals metric values for different web pages of a website from end users and then provide a report comparing the 75th percentile of the page loads with the corresponding thresholds.

Now let's look at computing the 75th percentile of the page loads, with one value per page load. There are two ways I am familiar with for computing the 75th percentile:

- Using an analytics database that takes the metric values of all page loads and provides ways to query for the required percentile over the values from a specified time range, such as a week or a month. These databases may also provide ways to override the value of a metric of a page load given the same id.

- Using a histogram provided by metrics systems such as Prometheus, which records the values as they arrive. These systems do not allow overriding the metric value of a page load if there is an update. In this case, I am wondering if there are any acceptable workarounds to obtain the correct or approximate percentile values.

In the absence of any workarounds, I was wondering if either of these two options is possible:

- Could we consider each update of the metric value for a certain page load as being values of different page loads?
- Could the browser-side JavaScript be made to send only one value per page load?

**Comment by scheler** [comment]
@philipwalton can you please comment on the above? Please let me know if it doesn't provide clarity.

**Comment by tunetheweb** [comment]
I can maybe answer some of your questions in a slightly different order than you posted them:

> Could the browser-side JavaScript be made to send only one value per page load?

By default the library will only report the final metric for the page view (with some caveats described below). You can set the [`reportAllChanges` flag](https://github.com/GoogleChrome/web-vitals#report-the-value-on-every-change) to report all metric changes, but that then depends on you handling this in your back end of update/override the current metric for that page which, as you mention, can be trickier.

The caveat is that for metrics that should be measured throughout the life of the page (CLS and INP), these are fired when the page is backgrounded, but may be fired again if a larger CLS or INP is created after the page is foregrounded again. If [your backend supports "delta" changes you can use that to only report the differences](https://github.com/GoogleChrome/web-vitals#report-only-the-delta-of-changes). 

> Could we consider each update of the metric value for a certain page load as being values of different page loads?

You could potentially do this as long as you are not using `reportAllChanges`, since it should only happen in limited circumstances as described above. It will affect the accuracy, but maybe not materially. Only you can really measure that, by attempting that and comparing to CrUX.

> Now let's look at computing the 75th percentile of the page loads, with one value per page load. There are two ways I am familiar with for computing the 75th percentile:
> 
> * Using an analytics database that takes the metric values of all page loads and provides ways to query for the required percentile over the values from a specified time range, such as a week or a month. These databases may also provide ways to override the value of a metric of a page load given the same id.
> * Using a histogram provided by metrics systems such as Prometheus, which records the values as they arrive. These systems do not allow overriding the metric value of a page load if there is an update. In this case, I am wondering if there are any acceptable workarounds to obtain the correct or approximate percentile values.

The first way is the only real way of doing this in my opinion. Or alternatively just grabbing all the data and calculating the p75 value in either a middle tier or the front end. The [Web Vitals Report](https://github.com/GoogleChromeLabs/web-vitals-report) does the p75 calculation in the front end after gathering all the data for the required timeframe. Note this can be a lot of data depending on your site traffic so can be slow and/or hit various limits (API limits, memory limits...etc.).

I don't see how the second way would work if you want to slice and dice you data in different ways - which is surely one of the main benefits of gather this data yourself rather than depending on CrUX.

**Comment by Tiggerito** [comment]
For 75th percentile I could not get a direct to Looker Studio report to work correctly. It always pre-aggregated the data making the 75th percentile closer to a 50th. I was also using GA4, which has recently been hit with a very tight API limit with Looker Studio.

So I moved to exporting GA4 to BigQuery, processing the data into a web_vitals table and using that for the report. Faster reports, no API limits and a more accurate 75th percentile.

Some of Barry's colleagues wrote an article on the concept:

https://web.dev/vitals-ga4/

And I wrote about my specific implementation:

https://bigcommerce.websiteadvantage.com.au/tag-rocket/articles/core-web-vitals-ga4-bigquery-data-studio/

**Comment by scheler** [comment]
@tunetheweb @Tiggerito thank you for the info and pointers, will review them.

@tunetheweb some metrics systems like Prometheus offer the dimensions functionality (via labels) in Histograms too, that can be used for slicing and dicing. Not sure about the accuracy though. Performance wise, it's likely faster than loading all the data to the frontend for percentile calculations.

**Comment by tunetheweb** [comment]
Closing this as don't think it's really a question about the web-vitals.js library, and more about the capabilities of the back end that the data the library is collecting and sending to.
