### ISSUE TITLE
TTFB distribution change on Sept 23rd

### ISSUE THREAD

**Issue by Tiggerito** [GoogleChrome/web-vitals#299]
Before Sept 23rd I was seeing a TTFB distribution in the way I would expect it for the CMS we work on (BigCommerce). Their servers take at least 600ms to respond.

![image](https://user-images.githubusercontent.com/4947018/209497120-492a939b-a6d6-4236-8c3a-f83e1972f467.png)

After the 23rd the distribution suddenly changed. With a major number of page views under 100ms

![image](https://user-images.githubusercontent.com/4947018/209497285-2736af74-7ce9-44eb-b6cb-67b9b9e9c120.png)

Digging into the data and it seems Safari had the biggest change, but the change with their 75th percentile being halved. A smaller reduction is noticeable in Chrome, Edge and Firefox. Even Samsung Internet

No code changes on our side were done near that time.

We're seeing this across multiple sites on the same CMS.

BigCommerce did introduce early hints with Cloudflare around that time. So one thought is the 103s are causing low TTFBs.

Any ideas on how to work out the cause of this change?

**Comment by Oscurz** [comment]
Please fix it

**Comment by tunetheweb** [comment]
103 Early Hints do count as “first bytes”, which some don’t agree with and [it is being discussed if this should be changed](https://github.com/w3c/resource-timing/issues/345).

And yes [this does still affect browsers like Safari that ignore 103 Early Hints](https://twitter.com/alonkochba/status/1584418869967740930?s=46&t=iMBKGHy4jEYbrXf_F7aCaw).

If looking to ignore the 103 Early Hibts aspect then chime in on above issue and/or use Server-Timing to measure this instead of TTFB.

**Comment by tunetheweb** [comment]
Closing this, as seems related to 103 rather than this library.
