### ISSUE TITLE
How is CLS Distance Fraction calculated?

### ISSUE THREAD

**Issue by Tiggerito** [GoogleChrome/web-vitals#311]
I'm trying to work out the distance fractions for CLS sources.

The [documentation I found](https://github.com/WICG/layout-instability#distance-fraction) is quite vague. Stating move distance with a simple example where a source moves down the page. Is that based on the changing top value?

But what if the height of the element also changed? Does it take that into account?

**Comment by tunetheweb** [comment]
As this comes directly from Chrome, rather than via this library, a better place to ask this question would be `https://groups.google.com/g/web-vitals-feedback` so going to close this, if you could repost there? And maybe comment with a link to that post here in case anyone else gets curious too!

BTW there is also some more docs here: https://web.dev/cls/#distance-fraction

**Comment by Tiggerito** [comment]
Will do
