### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by deasems** [GoogleChrome/web-vitals#36]
My team is unsure about tracking the metrics provided by this library. Rationale being that if we use these metrics then we'll be optimizing for Chromium-only browsers. 

What is your team's take on the value of tracking these metrics today given the level of browser support?

Is there support or commitment from other browser vendors to implement the APIs used to gather these metrics? Might be worth mentioning this in the docs.

**Comment by philipwalton** [comment]
> What is your team's take on the value of tracking these metrics today given the level of browser support?

Our take is that it's very important, even if some of the metrics are not reported in some browsers. Having partial insight into your real-world performance characteristics is much better than having no insight at all.

While there are subtle difference in browsers that may make certain things faster in certain engines, it's _extremely_ unlikely that work you do to improve LCP, FID, or CLS in Chrome will have a negative impact on other browsers.

The obvious exception to this is things that break other browsers (e.g. using [webp](https://caniuse.com/#feat=webp) to improve LCP in Chrome without implementing a fallback for Safari). But if you're testing your pages in all the browsers that you support (which you should be), then there's little risk of that happening.

Also note that most of the popular lab testing tools (e.g. Lighthouse, WebPagetest) are Chromium-based as well, and so the same concerns you raised apply there. The `web-vitals` library, however, is strictly better in that regard because at least some of the APIs are available in other browsers, and as more browsers add support, the library will automatically start reporting them.

> Is there support or commitment from other browser vendors to implement the APIs used to gather these metrics? Might be worth mentioning this in the docs.

These metrics were developed in the Web Performance Working Group, which has representation from all major browsers. As with all features, browsers implement the things they think will most benefit their users, so the best way to get cross-browser support for these APIs is to let other browser makers know (through their public issue trackers) that you want them.

**Comment by deasems** [comment]
Thanks @philipwalton, this will be helpful for my team. I will followup on Firefox/Safari's bug trackers as well.
