### ISSUE TITLE
Default behaviour of INP callback

### ISSUE THREAD

**Issue by seand52** [GoogleChrome/web-vitals#378]
Hi,

I'm trying to understand when the callback of the `onINP` function gets triggered with the default behaviour. I made a really basic repo with 2 buttons where one of them blocks the main thread for 2 seconds to simulate a high INP which you can find here https://github.com/seand52/basic-inp-example

I've noticed that the callback is not fired at all when interacting with the buttons, it seems to be fired when I open a new tab or visit a tab that is already opened. In the callback I want to send the data to some tracking service such as google analytics. I'm wondering if this is working as intended? With the default behaviour it seems that if a user enters my page, clicks on some stuff and closes it, this data would never be tracked because the callback would never be executed.

Are we supposed to use the option `{ reportAllChanges: true }` for that type of use case? From what I understand and the testing I've done, it seems that this option executes the callback in the first interaction, and any interaction which is slower than that. For example, if I have 3 interactions:
1. 50ms
2. 4000ms
3. 2000ms

It would execute the callback for the first and second interactions, but not the last one because we already had a slower one. This behaviour seems more useful so I'm wondering why it isn't the default behaviour?

Thanks

**Comment by tunetheweb** [comment]
Yes this is expected behaviour.

INP, like CLS, can only really be calculated at the end of the page life cycle. It looks like you README could do with a couple of small tweaks to make this clear so raixed #379 for that.

It is possible to report it earlier as you suggest, but that means it will be reported multiple times and many would prefer not to do that. And FYI, `{ reportAllChanges: true }` does still only report it if it's BIGGER than the previous one - exactly like you say - otherwise it's not a "change" in INP as such. So you can can go for this model if you wish.

> With the default behaviour it seems that if a user enters my page, clicks on some stuff and closes it, this data would never be tracked because the callback would never be executed.

Closing a page still triggers a visibility change [see this post for more details](https://developer.chrome.com/articles/page-lifecycle-api/) so that will still be reported. Of course if the browser crashes or the network send takes a while then it make no complete, but in general for most browsing closing the current page works.

What does not work, and the reason we report on visibility change, is if you close a backgrounded tab. Then that does not count as a visibility change and nothing is reported.

Note that doing the callback it on visibility change can still trigger multiple INP (and also CLS) reports (e.g. if you have a high INP, then background the tab, and then foreground it again, and then get a worse interaction). But at least it's less than doing it on every interaction (or even every worse interaction). In this case it can also be useful to report [the delta](https://github.com/GoogleChrome/web-vitals#report-only-the-delta-of-changes) to update the existing reported value if the backend supports that.

**Comment by seand52** [comment]
Hey @tunetheweb, thanks for the explanation, this makes sense now! 

Closing this issue as we can consider it as resolved
