### ISSUE TITLE
Document metric units

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/web-vitals#4]
It would be great if the README could document what units (seconds, ms, shifts etc) each metric is being reported back with. When I began using the library, I assumed it was just passing raw values back (where possible) from the WebPerf APIs but it would help to make this explicit. Perhaps include some examples of the values you'll likely get reported back and units?

**Comment by nicolalamacchia** [comment]
@philipwalton how is #13 adding information about the units? I would love to see some example of raw values returned and their actual meaning, since that is not obvious by just looking at the output. Furthermore, I agree with @addyosmani, I think it would be great to have the units returned explicitly, but that's outside the scope of documentation. I think this issue is still relevant though.

**Comment by arrygoo** [comment]
@addyosmani @nicolalamacchia did you end up finding out what the unit for the value is?

**Comment by philipwalton** [comment]
@arrygoo the units for each metric have been added to the documentation for each of the public functions in the API: https://github.com/GoogleChrome/web-vitals#functions

If there is something that's still not clear to you, can you please be specific about what it is?

**Comment by buck4chuka** [comment]
There are no units added to the link you shared
