### ISSUE TITLE
Functions as promises

### ISSUE THREAD

**Issue by ymschaap** [GoogleChrome/web-vitals#40]
Would it be possible to also support the async/await syntax if no callback is provided?

```
const data = await getCLS();
```

**Comment by philipwalton** [comment]
Thanks for the suggestion. That's actually how the API was originally designed, but it was converted in https://github.com/GoogleChrome/web-vitals/pull/3 to use callbacks instead because there were a few cases where the callback would need to be invoked more than once—which is a shame because the promise based approach is so much simpler!
