### ISSUE TITLE
Webpack Module is undefined

### ISSUE THREAD

**Issue by ifehrman** [GoogleChrome/web-vitals#416]
![image](https://github.com/GoogleChrome/web-vitals/assets/84200599/2c7d7382-6576-485f-b683-a7d2ace5d5d2)
![image](https://github.com/GoogleChrome/web-vitals/assets/84200599/42a03768-0d53-4d42-aa17-206def9fe246)
![image](https://github.com/GoogleChrome/web-vitals/assets/84200599/60225b37-b08a-4755-b00b-a6484d211737)

To whom this may concern,
I've installed the web vitals library and am trying to push the metric's to my dataLayer. I've followed the docs for installation but I am seeing an error saying the module is undefined. Has anyone seen this before or would have any insight as to how this can be resolved? I'd appreciate any feedback

**Comment by tunetheweb** [comment]
This isn't an issue with this library but more a React coding issue.

My limited understanding (because I am not a React developer) is you [cannot set a a script's content in that manner by rendering a `<script>` JSX element](https://stackoverflow.com/questions/34424845/adding-script-tag-to-react-jsx) and you need to either:
1. Export your `webVitals` function and simply call that in your main app JavaScript code. Which makes mroe sense as you can import web-vitals as a dependency. I tried that and it worked find.

or

2. Add the script element using the standard web apis (`document.createElement("script");`) if, for example, you wanted to reference web-vitals.js as an external dependency. Though I wouldn't recommend that,

**Comment by ifehrman** [comment]
Thank you very much for the response. I'll adjust my implementation
