### ISSUE TITLE
CLS being reported due to filter CSS transition

### ISSUE THREAD

**Issue by Magellol** [GoogleChrome/web-vitals#470]
Hello!

I was investigating various CLS reports on our app when I came across this one which seems to be triggered by a CSS `transition` with a `filter` property on a `:after` pseudo element. I'm not sure I understand why a `brightness` filter could cause a layout shift.

I was able to create a small reproducible example: https://codesandbox.io/p/sandbox/cls-after-el-filter-fxj5jn

Here's also a recording

https://github.com/GoogleChrome/web-vitals/assets/3819093/c9990e59-d668-4faf-8bd7-fd201915165c

**Note**: Replacing the `:after` pseudo element by a `span` removes the CLS entirely, i've got a second example here:
https://codesandbox.io/p/sandbox/no-cls-after-el-filter-df2s9s

### Backstory
We often create cards with this HTML/CSS structure to be able to make a whole card clickable while also providing other links inside it because we can't nest anchor tags. We use an `:after` pseudo element that we stretch over the whole card and z-index position other links above it.  This keeps every links accessible (tab navigation and whatnot).

The CLS is quite small here but in our case the magnitude is much higher (without actual visible shift) but I think we get numbers like `0.05` which is already half of the "good" threshold so we don't have much room left if other CLS are found.

I'm not sure if this is a bug on this library or a bug on our end so I'm looking for guidance. What do you think? I'm also curious if this is accounted for our overall CWV score or is strictly a potential false positive from this library and doesn't impact our score.

Let me know if you need more information. Thank you.

**Comment by tunetheweb** [comment]
This is a very interesting one! And I had to pull out some favours with some CSS colleagues to figure it out.

Apparently applying `filter` is one of the properties that creates a new stacking context so, as that's added and removed as you hover over it, that's causing a slight recalc in the CSS which technically causes a change in the pseudo elements position (even though there's no visible change to the user).

The easiest way to prevent this is to create that new stacking context in advance, by uncommenting one of the two properties below:

```css
      .overlay-container {
        transition: filter 0.2s ease-in-out;
        /* filter: brightness(1); */
        /* will-change: transform; */
```

The first (`filter: brightness(1);`) sets the filter property even in unhovered state to the default of 1 so it has a `filter` value and knows therefore that it needs it's own stacking context when you change this default later.

The second (`will-change: transform;`) explicitly tells the browser that it needs it's own stacking context as something is going to be transformed later. It's probably the cleaner of these two options as not explicitly tied to what transform you're going to do.

Should Chrome count this as CSS when there is no user-visible change? No, it probably shouldn't. So feel free to raise a bug at [crbug.com/new](https://crbug.com/new), however it's quite a minor one in this case (do let us know if you have a bigger example!) and it'll actually be over so slightly more performant to do the solution above, so I imagine it won't be the biggest priority to look at this.

Oh and btw, on that note, Chrome-specific issues should be raised to [crbug.com](https://crbug.com) rather than here, or to our [web-vitals-feedback group](https://groups.google.com/g/web-vitals-feedback). This repo is specifically for the web-vitals.js library and this issue could have been repeated with a layout-shift performance observer even outside the library (though you may not have realised that!).

**Comment by Magellol** [comment]
Thanks for looking into this and for the suggestions. I guess on our end, I still need to figure out why the numbers we're seeing are larger than the reproducible example I sent above but in the meantime, I'll apply your suggestion and move on.

>Oh and btw, on that note, Chrome-specific issues should be raised to [crbug.com](https://crbug.com/) rather than here, or to our [web-vitals-feedback group](https://groups.google.com/g/web-vitals-feedback). This repo is specifically for the web-vitals.js library and this issue could have been repeated with a layout-shift performance observer even outside the library (though you may not have realised that!).

That makes sense. I wasn't sure where the problem was, good to know for next time.

**Comment by tunetheweb** [comment]
> UPDATE: using the `will-change` property fixes the issue on our end as well 💯

Excellent! Great to hear.
