### ISSUE TITLE
Using `performance.eventCounts` instead of `performance.interactionCount`

### ISSUE THREAD

**Issue by ekremney** [GoogleChrome/web-vitals#491]
I couldn't find any reference to `performance.interactionCount` on web (except one W3 document). Also, both Google Chrome and Firefox don't seem to have it -> both returns `undefined`.

Suggesting to use the [performance.eventCounts](https://developer.mozilla.org/en-US/docs/Web/API/Performance/eventCounts) property instead of `interactionCount` to [`getInteractionCount`](https://github.com/GoogleChrome/web-vitals/blob/main/src/lib/polyfills/interactionCountPolyfill.ts#L49).

**Comment by mmocny** [comment]
The one w3 document I assume is [the Event Timing spec](https://www.w3.org/TR/event-timing/#dom-performance-interactioncount)?

Chrome has implemented this feature, but it is still behind a feature flag in Stable (or via experimental web platform features).  We expect to ship it in stable.

`eventCounts` is not possible to use as a way to estimate interactionCount (and its the reason Event Timing added interactionCount).  (You can also find lots of discussion in the Web Perf WG for this feature).

---

The single biggest flaw of eventCount is that it does not differentiate when e.g. pointer events actually become a scroll, or how keyboard events might trigger clicks, or how accessibility or IME interfaces might dispatch events in different orders...

You could try to approximate `interactionCount` but using something like the count of clicks - count of pointerCancel, and an earlier version of web-vitals.js actually tried that (especially since this is supported on Firefox).  Unfortunately it was off and unreliable on all browsers.

**Comment by ekremney** [comment]
that's a very clear explanation, thanks @mmocny!
