### ISSUE TITLE
Speculation rules can impact on increase values for INP ?

### ISSUE THREAD

**Issue by rashaReshana** [GoogleChrome/web-vitals#499]
Can someone please confirm that I have my CWV events set up correctly? or if Speculation rules can impact on increase values for INP ?

After I added the script in GTM to track my website performance and also added some speculation rules for only 4 pages that get a lot of traffic (based on GA4 page path exploration report to identify user behavior), I have had this code and the rules on my website for only one month now. When I compare the values for INP before and after adding the web vitals script and speculation rules to the website from the PageSpeed Insights field data report, I see the INP value increased from 593 to 744 on mobile, and also increased on desktop. So I'm not sure if the script or the speculation rules have anything to do with that, or if the data from PageSpeed Insights is not updated. Because if the PageSpeed data is based on CrUX, I don't see the data for June yet in the CrUX report. So I'm not sure if the PageSpeed data is from the previous month (May) or if adding the script and the speculation API rules will even affect the INP value. In my speculation rules, I only preload and prefetch 3 other pages, and that helped navigation between those pages take less time.

If someone can help give me some insight, I would appreciate it!

![web-vital](https://github.com/GoogleChrome/web-vitals/assets/174159765/47e7b445-35a1-4de6-910a-142fed81b4cb)
![Rules](https://github.com/GoogleChrome/web-vitals/assets/174159765/b3813a80-a2fc-4c4a-b639-4504182a55fa)
![after-01](https://github.com/GoogleChrome/web-vitals/assets/174159765/9c281e08-f869-4e5b-b933-d87cbe5d233e)
![before-01](https://github.com/GoogleChrome/web-vitals/assets/174159765/7154c729-7b80-4eab-89eb-e9ac38fbe99b)

**Comment by tunetheweb** [comment]
If I can summarise, you have added the web-vitals.js to your page for the first time and also added speculation rules, and have potentially seen a negative impact on INP? Is that correct?

If so, that's a little vague for us to investigate further and you'd need to narrow down whether this increase was due to 1) the addition of web-vitals.js, 2) the addition of speculation rules, 3) unrelated changes in your traffic or site, or 4) a combination of all of these.

We're of course very mindful of performance for this library so are not aware of it causing large increases in INP like this. It is also fully supportive of speculation rules.

Speculation Rules can cause more work to be done. You have not specified an [eagerness level](https://developer.chrome.com/docs/web-platform/prerender-pages#eagerness) so that means all 3 pages will prerender and prefetch immediately as you are using `list` rules. It also appears you are prerendering AND prefetching the same content which seems unnecessary.

But ultimately you need to investigate this issue more on your side. So closing this issue for now. Can reopen if you discover issues with the web-vitals library.
