### ISSUE TITLE
onINP trigger always when browser tab change ?

### ISSUE THREAD

**Issue by psppro26** [GoogleChrome/web-vitals#515]
Hello, i'm on react 18.3
I've a weird issue where ` onINP(handleINP, { reportAllChanges: false });` is triggered on console only when :  
1) click on button (nothing on console)
2) i change tab and go back ? ( inp triggered with poor performance)

more i wait before change tab , more the inp value is high ? 

Any idea ?

<img width="687" alt="Capture d’écran 2024-08-09 à 18 23 44" src="https://github.com/user-attachments/assets/e459e9ce-a60a-4b6f-ad8e-9f8f754a5ffd">

**Comment by philipwalton** [comment]
> I've a weird issue where ` onINP(handleINP, { reportAllChanges: false });` is triggered on console only when :
> 
> 1. click on button (nothing on console)
> 2. i change tab and go back ? ( inp triggered with poor performance)

Both of these are expected and by design. See the [`onINP()` documentation](https://www.npmjs.com/package/@rollup/plugin-node-resolve) for an explanation:

> [!IMPORTANT]
> INP should be continually monitored for changes throughout the entire lifespan of a page—including if the user returns to the page after it's been hidden/backgrounded. **However, since browsers often [will not fire additional callbacks once the user has backgrounded a page](https://developer.chrome.com/blog/page-lifecycle-api/#advice-hidden), `callback` is always called when the page's visibility state changes to hidden.** As a result, the `callback` function might be called multiple times during the same page load (see [Reporting only the delta of changes](#report-only-the-delta-of-changes) for how to manage this).

> more i wait before change tab , more the inp value is high ?
> 
> Any idea ?

This most likely has nothing to do with how long you wait; it most likely more about how many interactions you've done prior to changing tabs. The more interactions you perform, the more likely it is that some of those interactions are slow, resulting in a high INP score.

My suggestion would be to use the attribution data collected to understand why those interactions are taking a long time.
