### ISSUE TITLE
About PerformanceElementTiming API

### ISSUE THREAD

**Issue by St2r** [GoogleChrome/web-vitals#557]
Thanks for your working on this awesome lib.

Will this lib supports the [PerformanceElementTiming](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceElementTiming) API, which means we can collect performance metrics of specific element with `elementtiming` tag very easily, just like LCP or FCP.

**Comment by tunetheweb** [comment]
Can you explain how you would like the library to support this API?

At the moment the library’s aim is to encapsulate the best practices for measuring the Web Vitals metrics.

Element Timing is a great API to capture specific elements but does not require any addition considerations. (save perhaps not to report it if page is hidden first which the library does for FCP, and LCP but only on a best efforts manner since there’s currently no reliably way to detect this).

**Comment by St2r** [comment]
Got it.

I saw that you guys designed a very robust logic for LCP and FCP, so I thought the ElementTimingAPI also need that, but as you said, for specific elements using the native API is enough.

Thank you for your patience.
