### ISSUE TITLE
Questions about manually takeRecords

### ISSUE THREAD

**Issue by kkdev163** [GoogleChrome/web-vitals#56]
Hello, maintainers. I have a question about  [this line](https://github.com/GoogleChrome/web-vitals/blob/4607f9c5f49d6876f20efe3f82c71f2e55df8e2b/src/getLCP.ts#L52). 

when I start test server and navigate to http://localhost:9090/test/lcp, and then add some log to print records return by ```po.takeRecords()```, I find it's length always be 0. 

So, I don't know in which condition, we need to manually get records and its length will not be 0.

Please help me to understand this line, thanks.

**Comment by philipwalton** [comment]
> So, I don't know in which condition, we need to manually get records and its length will not be 0.

The `takeRecords()` method will usually return no entries, but in some cases it can happen (e.g. if `takeRecords()` is called in the same frame where a new LCP candidate has been discovered—but since the callback is run async, it hasn't been invoked yet).

The point of calling it in the line you referenced is to just make sure there aren't any pending entries prior to reporting the value.
