### ISSUE TITLE
Any plans to capture TTI?

### ISSUE THREAD

**Issue by nvlimbachiya** [GoogleChrome/web-vitals#59]
@philipwalton I notice that slowly the meaningful web metrics to collect have moved away from TTI to LCP these days. Can you shed some light on why that is the case after promoting TTI for the last couple of years by the webdev community?

I also noticed a [TTI measuring lib](https://github.com/GoogleChromeLabs/tti-polyfill) and have been using it for a few weeks now. Would you suggest me to stop using it and if not then any plans of integrating that into web-vitals?

~Nish

**Comment by philipwalton** [comment]
> I notice that slowly the meaningful web metrics to collect have moved away from TTI to LCP these days. Can you shed some light on why that is the case after promoting TTI for the last couple of years by the webdev community?

Sure, the answer is relatively simple. While TTI was a revolutionary metric when it was first introduced (i.e. the idea that a page wasn't really "loaded" until its main thread was free) we've since come up with better metrics (e.g. [FID](https://web.dev/fid/) and [TBT](https://web.dev/tbt/)) that more accurately measure the negative user experiences associated with poor interactivity.

The problem with TTI is that two sites with the same TTI might have vastly different load experiences (e.g. a page with a single, 10-second long task and a page with two, 51 ms tasks could have the same TTI).

> I also noticed a [TTI measuring lib](https://github.com/GoogleChromeLabs/tti-polyfill) and have been using it for a few weeks now. Would you suggest me to stop using it and if not then any plans of integrating that into web-vitals?

I would, we now only recommend measuring TTI [in the lab](https://web.dev/user-centric-performance-metrics/#in-the-lab
). In the field we recommend FID.

**Comment by nvlimbachiya** [comment]
Awesome, thank you for letting me know!
