### ISSUE TITLE
Why use Google Analytics Event tracking for reporting web vitals?

### ISSUE THREAD

**Issue by SukkaW** [GoogleChrome/web-vitals#80]
https://github.com/GoogleChrome/web-vitals#send-the-results-to-google-analytics

IMHO `User Timing Tracking` should be used. Google Analytics has been using `User Time Tracking` for `TTFB`, `DIT` (DOM Interactive), `DNS` (DNS Resolve Time) time. It supports non-integer value as well.

Example code:

```js
import {getCLS, getFID, getLCP} from 'web-vitals';

function sendToGoogleAnalytics({name, delta, id}) {
  // https://developers.google.com/analytics/devguides/collection/analyticsjs
  ga('send', 'event', {
  hitType: 'timing',
  timingCategory: 'Web Vitals',
  timingVar: name,
  timingValue: Math.round(name === 'CLS' ? delta * 1000 : delta)
});

getCLS(sendToGoogleAnalytics);
getFID(sendToGoogleAnalytics);
getLCP(sendToGoogleAnalytics);
```

**Comment by philipwalton** [comment]
It's definitely possible to user User Timing, but I don't generally recommend it because [timing hits are sampled at ~1%](https://developers.google.com/analytics/devguides/collection/analyticsjs/user-timings) (depending on site traffic), which is enforced both on the client and the server (so there's no way around it). Events do not have this same restriction.

Also, timing hits (as far as I know) are not supported in the [new version of Google Analytics](https://support.google.com/analytics/answer/10089681), whereas events are supported in both.
