### ISSUE TITLE
onReport data can't be changed

### ISSUE THREAD

**Issue by aaarichter** [GoogleChrome/web-vitals#97]
Hello,

I noticed that the entries in the `onReport` data contains references to DOM notes, in the `entries` properties: `element` (CLS), `target` (FID) and `sources` (LCP). 
Unfortunately these properties can't be changed or updated to be JSON safe due to the lack of a setter.

Q1: Is it possible to get the setters back?
Q2: Instead of referenced elements, is it possible to have an XPath.

**Comment by philipwalton** [comment]
> Q1: Is it possible to get the setters back?

I'm not sure what you mean by this. Can you clarify?

**Comment by aaarichter** [comment]
@philipwalton so when I try to overwrite, set or delete an existing key/value pari I will receive a TypeError:

Example with CLS data
```js
function onResponse(data) {
  data.entries.forEach(entry => {
    if (entry.element) {
      // This fails with Uncaught TypeError: Cannot set property element of #<LargestContentfulPaint> which has only a getter
      entry.element = getXPathForElement(entry.element);
    }
  });
  /*...*/
}
```

**Comment by philipwalton** [comment]
Thanks, I understand your issue now. However, this isn't something that the web-vitals library can change, since the entry your code is trying to write to is spec'ed to be read-only. See the [`LargestContentfulPaint` interface](https://wicg.github.io/largest-contentful-paint/#sec-largest-contentful-paint-interface) for details.

I'd recommend copying the data you want from the entry into your own object. That way you can use whatever format you like.

**Comment by aaarichter** [comment]
Okay I see. I ended up with the same solution as you suggested.
 
Maybe a note in the project's readme, that the fields are not mutable, can help others that run into a similar issue.

Closing the ticket
