### ISSUE TITLE
LCP still relevant on hidden pages

### ISSUE THREAD

**Issue by smhmic** [GoogleChrome/web-vitals#99]
Why should LCP not be measured while the page is hidden? I understand we're measuring RUM, and if the page is hidden it's not affecting UX, but it's still relevant data because LCP still reflects how the page is loading.  And if we only consider a subset of LCP values then it could skew the metric. (i.e. what if half of users open a page from an <a target="_blank"> link, and then switch to the page, then we're ignoring the first few seconds of LCP values (probably the largest ones) for half of tracked users.)

**Comment by philipwalton** [comment]
> Why should LCP not be measured while the page is hidden?

Because it usually doesn't measure the load time of the largest contentful element, it measures the time until the user focused that page—which is not what you typically want to measure.

To clarify, consider a scenario:

1. At exactly 9:00 a.m. You load a web page in a background tab and leave it there.
2. At exactly 10:00 a.m. You foreground that tab for the first time.

In this scenario, LCP will be 1 hour (3,600,000 ms), which doesn't reflect how long it took to load the page, as the page was likely loaded (though not painted) long before the user viewed it.

So while the API itself does expose this information in the event that it might be useful in some cases, the Chrome User Experience Report (CrUX) does not consider LCP for pages loaded in the background, and this library measures the metrics as they're measured by CrUX

**Comment by philipwalton** [comment]
I'm going to close this as I don't think there's any changes we need to make to this library. Any developer who wants to know the LCP of pages loaded in the background can use the native API.
